### ISSUE TITLE
errorMessage : timeOut

### ISSUE THREAD

**Issue by hybridapp20161** [bluedesign/speech-recognition-feat-siri#1]
Hi,
We have implemented your plugin in our app but everytime it goes to onError function and give errorMessage : timeOut.
Standalone application which you have provided is working fine.
Could you please help.

**Comment by bluedesign** [comment]
@hybridapp20161 , Can you tell me the version of Apache Cordova and cordova ios of your development environment.

**Comment by hybridapp20161** [comment]
My cordova version:6.3.1
xcode:Version 8.0 (8A218a)
IOS:OS X EI Capitan..10.11.6 (15G1004)
cordova ios:4.0.1

**Comment by bluedesign** [comment]
Thank you for information.
I tried to verify created a new blank project of Cordova.

When I check in the iOS simulator, it will time out (I do not know how to test the voice recognition on the simulator), 
but Speech recognition Once actually run the program in the iOS device has function.
Please try again the sample code to reference.

### Environment:

cordova: 6.3.1
cordova ios: 4.2.1

Xcode: 8.0 (8A218a)
Swift Compiler version: 3

iOS device: iPhone5(iOS 10.1.1)

### plugin

```
bluedesign-no-MacBook-Air:CDVSpeakToMe bluedesign$ cordova plugin ls
cordova-plugin-speech-recognition-feat-siri 1.0.1 "Speech Recognition feat. Siri"
cordova-plugin-whitelist 1.3.0 "Whitelist"
bluedesign-no-MacBook-Air:CDVSpeakToMe bluedesign$ 
```

### Test Code

index.html:

```
<body>
    <div class="app">
        <h1>Apache Cordova</h1>
        <div id="deviceready" class="blink">
            <p class="event listening">Connecting to Device</p>
            <p class="event received">Device is Ready</p>
        </div>
        <div>
            <input type="button" id="btn" value="Start Speech Recognition" />
        </div>
    </div>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="js/index.js"></script>
</body>
```

index.js:

```
onDeviceReady: function() {
    app.receivedEvent('deviceready');

    var reccordButton = document.getElementById("btn");
    reccordButton.onclick = function() {
        if(SpeechRecognition) {
            SpeechRecognition.recordButtonTapped(
                '15',  // ex. 15 seconds limitation for Speech
                function(returnMessage){
                    alert(returnMessage); // onSuccess
                },
                function(errorMessage) {
                    console.log(errorMessage); // onError
                }
            )
        }
    };
},
```

### Screen shot

<img src="https://cloud.githubusercontent.com/assets/14952627/19956925/b2e06b34-a1d4-11e6-9025-f5f8129e5113.PNG" width="320">

**Comment by hybridapp20161** [comment]
Have updated
Environment:

cordova: 6.3.1
cordova ios: 4.2.1

Xcode:  8.1 (8B62)
Swift Compiler version: 3

iOS device: iPhone5(iOS 10.1.1)(14B100)

still it is going in onError function with error message timeOut.

**Comment by bluedesign** [comment]
Does this command in a terminal software you are running?

```
 cordova prepare ios
```

**Comment by bluedesign** [comment]
### Premise to use the speech recognition feature by using this plug-in

The user will enter a state of waiting voice and press once the button on the UI. 
User terminates the voice recognition by pressing the button on the UI again When you have entered the voice. 
The plug-in converts the voice that has been entered during the two click event to text

Interface to action users start and end of the speech recognition is the same as the sample code "SpeakToMe" that Apple has to offer.

**Comment by bluedesign** [comment]
I hope find the best plugin for you thanks.

**Comment by hybridapp20161** [comment]
Hi,
Your plugin is working but it require double tap for startListening and stopListening also there is no UI for your plugin makes it difficult to recognize when to speak.

Thanks for all your help.
