### ISSUE TITLE
Application getting crashed below ios 10

### ISSUE THREAD

**Issue by hybridapp20161** [bluedesign/speech-recognition-feat-siri#10]
API is working fine for ios 10 and above,but getting crash for below ios 10.We are okay if not compatible for below version but the app should not get crash.Currently we are removing voice plugin in order to run the app for below ios 10 version.
Please share some workaround so that our app can work properly for below ios 10 version.

**Comment by bluedesign** [comment]
Hi, hybridapp20161
This is a plugin specialized to call Siri 's API.
It will not correspond to iOS 9 or earlier in the future.

https://developer.apple.com/library/content/samplecode/SpeakToMe/Introduction/Intro.html

**Comment by bluedesign** [comment]
Not a bug.
