### ISSUE TITLE
Pre-requisites - certificates etc

### ISSUE THREAD

**Issue by adamgins** [bluedesign/speech-recognition-feat-siri#11]
Hi, 

very interesting package. Thanks... I am keen to see if I can use this.

could you please confirm what we need to get a basic example running?

I see the following in XCode 
<img width="723" alt="screen shot 2017-04-17 at 5 55 15 pm" src="https://cloud.githubusercontent.com/assets/7233741/25082944/3bfded12-2397-11e7-870c-e12697dd2204.png">

Do we need this on and do we need to generate app and matching provisioning profiles?

Also please confirm can you run this on iOS Simulator? If so, how do we do this?

I am getting a 'timeOut' error in the simulator and was not sure if it's a configuration issue or just that it does not run in the simulator?

thanks

**Comment by bluedesign** [comment]
hi, adamgins!
thanks for your information.

Debugging of the application incorporating the plug-in does not work with iOS simulator. Please execute using iOS device. I tried it with Xcode 8.3.1 but after all it did not work with iOS simulator.
When running with iOS simulator, plug-in always judges time-out. That movement is exactly right.

Preparing a provisioning profile is the same as making an iOS native app.

**Comment by adamgins** [comment]
Thanks. Got it going on my phone. 

Adam Ginsburg
adam.ginsburg@buzzy.buzz
tel: +61 411 151 732
www.buzzy.buzz
