### ISSUE TITLE
After upgrading the plug-in version, various errors have come up and it is in trouble.

### ISSUE THREAD

**Issue by hybridapp20161** [bluedesign/speech-recognition-feat-siri#12]
Hi All,
I have been using this plugin for long.
Now I dont want to wait for hard coded 15 sec for the mike to stop,I would like it to disapper as soon as user stops speaking,thus detecting the pause in users voice.
Is there any method to dynamically stop the mike as soon as user stops speaking??

**Comment by bluedesign** [comment]
It is implemented in version 2.0.0

**Comment by hybridapp20161** [comment]
Hi Bluedesign,
for the mike to dynamically stop,is it still required to give the time limit

**Comment by hybridapp20161** [comment]
Actually , I want the mike to detect the end of voice and stop as soon as no voice is recognised,
What I cant understand here is if we give the Limitation Seconds ,how will it behave dynamically.

Right now after adding the update plugin to my code ,I am getting "Wrong Number of arguments(3 for 4)" on mike click.

Thanks in advance for your solution

**Comment by bluedesign** [comment]
PTAL
https://github.com/bluedesign/speech-recognition-feat-siri#new-features--releasesv210

**Comment by hybridapp20161** [comment]
Hi 
Thanks for the help, the plugin is working fine .
I just have one doubt ,everytime I speak something :
[Utility] +[AFAggregator logDictationFailedWithError:] Error Domain=kAFAssistantErrorDomain Code=203 "Retry" UserInfo={NSLocalizedDescription=Retry, NSUnderlyingError=0x17465a3a0 {Error Domain=SiriSpeechErrorDomain Code=1 "(null)"}}
pops up after executing my code and if in between i am pressing the mike button ,the code pops up invalid input without letting me speak.

I checked on internet and found that this is some unknown parameter received error,however no solution is given to rectify it.

I am clueless now how to solve it,because the mike will keep on showing invalid input if I press it between the time I get this error
