### ISSUE TITLE
speech siri not compiling in other versions

### ISSUE THREAD

**Issue by hybridapp20161** [bluedesign/speech-recognition-feat-siri#14]
Hi,
I suppose speach plugin is for ios 10 and above .That is ok.
But when compiling and running it on lower OS my app is crashing.
If this plugin is not working for lower versions its fine,But i need it not to crash my app on lower versions.
I need the same exe to work for all devices,so I dont have to maintain separate exes .
Please help me with this

**Comment by bluedesign** [comment]
@hybridapp20161 
I can not deal with an application that assumes a previous iOS version that I do not support.
Consult the contributors of Apache Cordova.

**Comment by bluedesign** [comment]
#10
