### ISSUE TITLE
Request for variable change/Android compatibility

### ISSUE THREAD

**Issue by adamgins** [bluedesign/speech-recognition-feat-siri#15]
Hi 

again, great plugin.  We're foing some cool stuff with it https://www.youtube.com/watch?v=y57DuUSZPNE

I know need to get this working with Android.

There are a couple of other plugins out there and from a quick try they don't have the detection of the end of conversation, which you have conquered.

So I was thinking of installing https://github.com/pbakondy/cordova-plugin-speechrecognition howver their global variable is called `SpeechRecognition` too. So I get a conflict.

Is it possible to change this one to `SpeechRecognitionSiri` please?

Or any plans to support Android?

thanks again

BTW,I did clone and change here https://github.com/Buzzy-Buzz/speech-recognition-feat-siri happy to make a pull request... but up to you?

**Comment by bluedesign** [comment]
@adamgins 
I saw the service you introduced on youtube
It's a very good service

About this plug-in
As the corresponding platform is a policy to keep it simple
There is no plan to respond to android.

But
In the future, we will review the unique name so as not to conflict with other plugins.
And I will rename some file names as well.
Please wait one more day.

**Comment by bluedesign** [comment]
hi, @adamgins
Even in the case of your suggested global variable "SpeechRecognitionSiri", I changed to "SpeechRecognitionFeatSiri" because there is a possibility that conflicts with other plugin names will continue in the future.
thanks.

**Comment by adamgins** [comment]
Hi @bluedesign 
Awesome, thanks for the quick turnaround!!!

**Comment by bluedesign** [comment]
Thanks to you I have reviewed the plugin's naming rules with this Issue
