### ISSUE TITLE
Siri plugin support 

### ISSUE THREAD

**Issue by DeepthiKR444** [bluedesign/speech-recognition-feat-siri#19]
Hello,
I want to start plugin using phonegap.. does this plugin supported in phonegap?
and It supports from IOS 10 and does it is supported only in iPhone 7 plus?

**Comment by bluedesign** [comment]
Hello, DeepthKR444.
This plugin was targeted to iOS applications running iOS 10 or later OS.
However, the PhoneGap application has not checked its operation. Please try it

**Comment by bluedesign** [comment]
Since there is no reply, we will close it.
