### ISSUE TITLE
what does returnMessage do?

### ISSUE THREAD

**Issue by william76101** [bluedesign/speech-recognition-feat-siri#2]
is returnMessage for translating from speech to text? I will be able to see the text after speak?

I was trying to get your plugin to work with ionic but console didn't show the text of returnMessage. Can you advise on this? Thanks :)

**Comment by bluedesign** [comment]
hi!
@williamtay7

>is returnMessage for translating from speech to text? I will be able to see the text after speak?

That's right.
The plug-in returns the result of speech recognition as text data.


>I was trying to get your plugin to work with ionic but console didn't show the text of returnMessage. Can you advise on this? Thanks :)

How did you validate the behavior of the plugin?
Is it an iOS simulator? Or is it an actual machine?

**Comment by bluedesign** [comment]
Please also refer to the sample code posted to Issue here.
thanks.

https://github.com/bluedesign/speech-recognition-feat-siri/issues/1

**Comment by william76101** [comment]
Thanks @bluedesign!! I got your plugin to back to working. 👍

**Comment by bluedesign** [comment]
Was good!
