### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by ngt14** [bluedesign/speech-recognition-feat-siri#21]
Hi, i want to use this plugin but all my code in Cordova is in Objective-C language and not Swift language, how can i resolved it ?

**Comment by bluedesign** [comment]
こんにちは
私が作ったCordovaをベースにしたアプリケーションは迅速に使うのではなく、プラグインを組み込むことができます。

**Comment by bluedesign** [comment]
Have you tried installing the plugin?

**Comment by bluedesign** [comment]
Since there is no reply, we will close it.
