### ISSUE TITLE
TimeOut error

### ISSUE THREAD

**Issue by nileshaut25** [bluedesign/speech-recognition-feat-siri#6]
Hi Bluedesign,

I am trying to use your plugin in one of my projects, its working fine as a sample code but when I am trying to add new lines to your sample code it is giving me TimeOut error.

`if(SpeechRecognition) {
SpeechRecognition.recordButtonTapped(
   '15',  // ex. 15 seconds limitation for Speech
function(returnMessage){
alert(returnMessage); // onSuccess
if(returnMessage){
alert(returnMessage); // onSuccess
showmsg(returnMessage);
}
   },
   function(errorMessage) {
alert(errorMessage); // onError
   }
)
}`

This showing me alert messages before and after the "If statement" but after that instead of going to "showmsg()" function its giving the "timeOut error".

Please Help.

**Comment by bluedesign** [comment]
Hi, nileshaut25
Code executed.
It is a problem of Javascript function showmsg () you wrote.

![2017-01-16 23 09 39](https://cloud.githubusercontent.com/assets/14952627/21986209/e73d2a0a-dc41-11e6-8dcb-e4619c45109c.png)

![img_2327](https://cloud.githubusercontent.com/assets/14952627/21986251/10739134-dc42-11e6-9cdd-135922412281.PNG)

**Comment by nileshaut25** [comment]
Solve the issue.
Didn't get "this" reference of object in my method. Make changes in code and its work.
