### ISSUE TITLE
Legacy Swift Language Version

### ISSUE THREAD

**Issue by atnpgo** [bluedesign/speech-recognition-feat-siri#8]
Adding the plugin to an existing Cordova project causes build to fail with the message:
 `"Use Legacy Swift Language Version" (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

Conversion fails and so does setting the "Use Legacy Swift Language Version" to either "Yes" or "No". Removing the plugin resolves the issue.

I've set the target iOS version to 10.0, set the values for NSMicrophoneUsageDescription and NSSpeechRecognitionUsageDescription. Is there anything special I need to get the project to build once this plugin is added?

Current Setup:
* Xcode: Version 8.2.1 (8C1002)
* Node.js : v6.9.4
* npm : 4.1.2
* Apache Cordova : 6.5.0
* cordova ios : 4.3.1

**Comment by bluedesign** [comment]
hi, Etienne Pageau
Thank you for the information
I think you are doing the necessary settings
Please also check here

1. Does your Cordova project have any other plug-ins written in Swift language or Swift code written by yourself?

2. Please check the version of Swift compiler with terminal.app

`$ swift -v`

(my environment) 
`aoyama-no-MacBook-Air:www bluedesign$ swift -v
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)`

**Comment by atnpgo** [comment]
Hi,

Adding `<preference name="deployment-target" value="10.0" />` and setting "Use Legacy Swift Language Version" to "No" seems to have resolved the issue.

Thank you for your time.
