### ISSUE TITLE
Should be possible to override the locale used

### ISSUE THREAD

**Issue by tormodboga** [bluedesign/speech-recognition-feat-siri#9]
By default it uses the system locale as the speech recognition language.. but it should be possible to override this..

By the way, the plugin works great! Good job..

**Comment by bluedesign** [comment]
hi, @tormodboga 
I know. If it does not specify a locale individually, it adopts the system locale of iOS device.
What is the Issue you have?

**Comment by tormodboga** [comment]
I was just thinking it should be possible to override the locale when using your plugin.. so you can have English language on the iPad itself, but use Spanish for speech recognition for example..

But I have found a few other plugins that supports speech on Android & iOS and also overrides the locale, so I will continue to use those.

**Comment by bluedesign** [comment]
Thanks for your comment
Indeed, I understand.
Even if we support locale switching in the future, there is no plan to support the android device, so I think it would be better to choose another excellent plugin.

**Comment by bluedesign** [comment]
Fixed as locale setting supported To do.
